#!/usr/bin/env bash

function e_warn()
{
  echo -e " \033[1;33m✖\033[0m  $*"
}

if [ -a /etc/debian_version ]; then
    sudo apt modernize-sources --yes
    if ! grep --quiet non-free /etc/apt/sources.list.d/debian.sources; then
      echo "/etc/apt/sources.list.d/debian.sources doesn't have nonfree"
      echo "exit when you're happy"
      bash --rcfile <(echo "PS1='subshell > '") -i
    fi
    # TODO: check for installer mount, I forget what it leaves these days
    if grep -r "^deb cdrom" /etc/apt/sources.list.d; then
      echo "/etc/apt/sources.list.d/ is still useing installer mount"
      echo "exit when you're happy"
      bash --rcfile <(echo "PS1='subshell > '") -i
    fi
    sudo apt-get update
    sudo apt-get install vim tmux git curl wget
else
    e_warn "not debian, doing nothing"
fi
