#!/usr/bin/env bash

sudo sed -i 's/# \(en_DK.UTF-8 UTF-8\)/\1/' /etc/locale.gen
sudo sed -i 's/# \(en_US.UTF-8 UTF-8\)/\1/' /etc/locale.gen
sudo locale-gen
echo "LANG=en_US.UTF-8" | sudo tee /etc/default/locale
