#!/usr/bin/env bash

curl -fLo ~/.vim/autoload/plug.vim --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
# Download Vim plugins.
if command -v vim >/dev/null; then
    vim +PlugUpgrade +PlugUpdate +qall
fi
