#!/usr/bin/env bash
set -euo pipefail

GITHUB_KEY_TYPE=ed25519

github_remote_works() {
    ssh -T -o StrictHostKeyChecking=accept-new git@github.com 2>&1 | grep -q "successfully authenticated"
}

setup_github() {
    read -r -p "Brand new keys? [Y/n] " response
    case "$response" in
        [nN][oO]|[nN])
            echo "Alright setup your own key"
            read -n 1 -s -r -p "Press the any key when you're happy"
            echo ""
            return
            ;;
    esac
    ssh-keygen -t "$GITHUB_KEY_TYPE" -N '' -f  ~/.ssh/"github_$GITHUB_KEY_TYPE"
    cat "$HOME/.ssh/github_${GITHUB_KEY_TYPE}.pub"
    echo "Add that to github, either by link or gh"
    echo "https://github.com/settings/ssh/new"
    echo "gh ssh-key add <(echo "\"$(cat ~/.ssh/github_ed25519.pub)\"" )"
    read -n 1 -s -r -p "Press any key to continue"
    echo ""
}

if [ ! -f ~/.ssh/"github_$GITHUB_KEY_TYPE" ]; then
    read -r -p "Setup github keys? [y/N] " response
    case "$response" in
        [yY][eE][sS]|[yY])
            setup_github
            ;;
        *) exit 0 ;;
    esac
fi

# TODO: get ~/.ssh/config setup properly

if github_remote_works ; then
    echo "github key works"
    if ! grep -q "pretend everything is git not https" ~/.gitconfiglocal 2>/dev/null ; then
        cat <<EOF >> ~/.gitconfiglocal
# pretend everything is git not https
[url "git@github.com:"]
    insteadOf = https://github.com/
EOF
        echo "using ssh instead of https forevermore"
    fi
else
    echo "github keys aren't setup properly, good luck"
    exit 1
fi
