#!/bin/bash
set -euo pipefail

# TODO: change to ed25519 also in git config
GITHUB_KEY_TYPE=rsa

github_remote_works() {
    ssh -T -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no git@github.com 2>&1 | grep -q "successfully authenticated" 
}

setup_github() {
    read -r -p "Brand new keys? [Y/n] " response
    case "$response" in
        [nN][oO]|[nN])
            echo "Alright setup your own key"
            read -n 1 -s -r -p "Press the any key when you're happy"
            echo ""
            return
            ;;
    esac
    ssh-keygen -t "$GITHUB_KEY_TYPE" -N '' -f  "~/.ssh/github_$GITHUB_KEY_TYPE"
    cat "~/.ssh/github_$GITHUB_KEY_TYPE".pub
    echo "Add that to github"
    read -n 1 -s -r -p "Press any key to continue"
    echo ""
}

if [ ! -f "~/.ssh/github_$GITHUB_KEY_TYPE" ]; then
    read -r -p "Setup github keys? [y/N] " response
    case "$response" in
        [yY][eE][sS]|[yY])
            setup_github
            ;;
        *) exit 0 ;;
    esac
fi
if  github_remote_works ; then
    if ! grep -q "pretend everything is git not https" ~/.gitconfiglocal ; then
        cat <<EOF >> ~/.gitconfiglocal
# pretend everything is git not https
[url "git@github.com:"]
    insteadOf = https://github.com/
EOF
    fi
    echo "github works, using ssh instead of https forevermore"
else
    echo "github keys aren't setup properly, good luck"
    exit 1
fi
